version: 2
jobs:
   build:
     docker:
       - image: circleci/python:3.6
     steps:
       - checkout
       - run:
           working_directory: python
           name: Install dependencies
           command: |
             python3 -m venv venv
             . venv/bin/activate
             pip install .
             pip install -r requirements-test.txt
       - run:
           working_directory: python
           name: Run tests
           command: |
             . venv/bin/activate
             pytest
