# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: golem_task_api/proto/envs.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='golem_task_api/proto/envs.proto',
  package='golem_task_api',
  syntax='proto3',
  serialized_options=_b('\202\262\031\ndocker_cpu\212\262\031\ndocker_gpu'),
  serialized_pb=_b('\n\x1fgolem_task_api/proto/envs.proto\x12\x0egolem_task_api\x1a google/protobuf/descriptor.proto\"E\n\x13\x44ockerPrerequisites\x12\r\n\x05image\x18\x01 \x01(\t\x12\x0b\n\x03tag\x18\x02 \x01(\t\x12\x12\n\nextra_vars\x18\x03 \x01(\t:9\n\x11\x44OCKER_CPU_ENV_ID\x12\x1c.google.protobuf.FileOptions\x18\xa0\x96\x03 \x01(\t:9\n\x11\x44OCKER_GPU_ENV_ID\x12\x1c.google.protobuf.FileOptions\x18\xa1\x96\x03 \x01(\tB\x1c\x82\xb2\x19\ndocker_cpu\x8a\xb2\x19\ndocker_gpub\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])


DOCKER_CPU_ENV_ID_FIELD_NUMBER = 52000
DOCKER_CPU_ENV_ID = _descriptor.FieldDescriptor(
  name='DOCKER_CPU_ENV_ID', full_name='golem_task_api.DOCKER_CPU_ENV_ID', index=0,
  number=52000, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=_b("").decode('utf-8'),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)
DOCKER_GPU_ENV_ID_FIELD_NUMBER = 52001
DOCKER_GPU_ENV_ID = _descriptor.FieldDescriptor(
  name='DOCKER_GPU_ENV_ID', full_name='golem_task_api.DOCKER_GPU_ENV_ID', index=1,
  number=52001, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=_b("").decode('utf-8'),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)


_DOCKERPREREQUISITES = _descriptor.Descriptor(
  name='DockerPrerequisites',
  full_name='golem_task_api.DockerPrerequisites',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='golem_task_api.DockerPrerequisites.image', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tag', full_name='golem_task_api.DockerPrerequisites.tag', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='extra_vars', full_name='golem_task_api.DockerPrerequisites.extra_vars', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=154,
)

DESCRIPTOR.message_types_by_name['DockerPrerequisites'] = _DOCKERPREREQUISITES
DESCRIPTOR.extensions_by_name['DOCKER_CPU_ENV_ID'] = DOCKER_CPU_ENV_ID
DESCRIPTOR.extensions_by_name['DOCKER_GPU_ENV_ID'] = DOCKER_GPU_ENV_ID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DockerPrerequisites = _reflection.GeneratedProtocolMessageType('DockerPrerequisites', (_message.Message,), {
  'DESCRIPTOR' : _DOCKERPREREQUISITES,
  '__module__' : 'golem_task_api.proto.envs_pb2'
  # @@protoc_insertion_point(class_scope:golem_task_api.DockerPrerequisites)
  })
_sym_db.RegisterMessage(DockerPrerequisites)

google_dot_protobuf_dot_descriptor__pb2.FileOptions.RegisterExtension(DOCKER_CPU_ENV_ID)
google_dot_protobuf_dot_descriptor__pb2.FileOptions.RegisterExtension(DOCKER_GPU_ENV_ID)

DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
