# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: golem_task_api/proto/golem_task_api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='golem_task_api/proto/golem_task_api.proto',
  package='golem_task_api',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n)golem_task_api/proto/golem_task_api.proto\x12\x0egolem_task_api\">\n\x11\x43reateTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x18\n\x10task_params_json\x18\x02 \x01(\t\"\x11\n\x0f\x43reateTaskReply\"%\n\x12NextSubtaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"C\n\x10NextSubtaskReply\x12\x12\n\nsubtask_id\x18\x01 \x01(\t\x12\x1b\n\x13subtask_params_json\x18\x02 \x01(\t\"R\n\x0e\x43omputeRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x12\n\nsubtask_id\x18\x02 \x01(\t\x12\x1b\n\x13subtask_params_json\x18\x03 \x01(\t\"\x0e\n\x0c\x43omputeReply\"4\n\rVerifyRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x12\n\nsubtask_id\x18\x02 \x01(\t\"\x1e\n\x0bVerifyReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x15\n\x13RunBenchmarkRequest\"\"\n\x11RunBenchmarkReply\x12\r\n\x05score\x18\x01 \x01(\x02\x32\xe0\x02\n\x11RequestorGolemApp\x12R\n\nCreateTask\x12!.golem_task_api.CreateTaskRequest\x1a\x1f.golem_task_api.CreateTaskReply\"\x00\x12U\n\x0bNextSubtask\x12\".golem_task_api.NextSubtaskRequest\x1a .golem_task_api.NextSubtaskReply\"\x00\x12\x46\n\x06Verify\x12\x1d.golem_task_api.VerifyRequest\x1a\x1b.golem_task_api.VerifyReply\"\x00\x12X\n\x0cRunBenchmark\x12#.golem_task_api.RunBenchmarkRequest\x1a!.golem_task_api.RunBenchmarkReply\"\x00\x32\xb7\x01\n\x10ProviderGolemApp\x12I\n\x07\x43ompute\x12\x1e.golem_task_api.ComputeRequest\x1a\x1c.golem_task_api.ComputeReply\"\x00\x12X\n\x0cRunBenchmark\x12#.golem_task_api.RunBenchmarkRequest\x1a!.golem_task_api.RunBenchmarkReply\"\x00\x62\x06proto3')
)




_CREATETASKREQUEST = _descriptor.Descriptor(
  name='CreateTaskRequest',
  full_name='golem_task_api.CreateTaskRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='golem_task_api.CreateTaskRequest.task_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='task_params_json', full_name='golem_task_api.CreateTaskRequest.task_params_json', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=123,
)


_CREATETASKREPLY = _descriptor.Descriptor(
  name='CreateTaskReply',
  full_name='golem_task_api.CreateTaskReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=142,
)


_NEXTSUBTASKREQUEST = _descriptor.Descriptor(
  name='NextSubtaskRequest',
  full_name='golem_task_api.NextSubtaskRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='golem_task_api.NextSubtaskRequest.task_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=181,
)


_NEXTSUBTASKREPLY = _descriptor.Descriptor(
  name='NextSubtaskReply',
  full_name='golem_task_api.NextSubtaskReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='subtask_id', full_name='golem_task_api.NextSubtaskReply.subtask_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subtask_params_json', full_name='golem_task_api.NextSubtaskReply.subtask_params_json', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=250,
)


_COMPUTEREQUEST = _descriptor.Descriptor(
  name='ComputeRequest',
  full_name='golem_task_api.ComputeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='golem_task_api.ComputeRequest.task_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subtask_id', full_name='golem_task_api.ComputeRequest.subtask_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subtask_params_json', full_name='golem_task_api.ComputeRequest.subtask_params_json', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=252,
  serialized_end=334,
)


_COMPUTEREPLY = _descriptor.Descriptor(
  name='ComputeReply',
  full_name='golem_task_api.ComputeReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=336,
  serialized_end=350,
)


_VERIFYREQUEST = _descriptor.Descriptor(
  name='VerifyRequest',
  full_name='golem_task_api.VerifyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='golem_task_api.VerifyRequest.task_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subtask_id', full_name='golem_task_api.VerifyRequest.subtask_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=352,
  serialized_end=404,
)


_VERIFYREPLY = _descriptor.Descriptor(
  name='VerifyReply',
  full_name='golem_task_api.VerifyReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='golem_task_api.VerifyReply.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=406,
  serialized_end=436,
)


_RUNBENCHMARKREQUEST = _descriptor.Descriptor(
  name='RunBenchmarkRequest',
  full_name='golem_task_api.RunBenchmarkRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=438,
  serialized_end=459,
)


_RUNBENCHMARKREPLY = _descriptor.Descriptor(
  name='RunBenchmarkReply',
  full_name='golem_task_api.RunBenchmarkReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='score', full_name='golem_task_api.RunBenchmarkReply.score', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=461,
  serialized_end=495,
)

DESCRIPTOR.message_types_by_name['CreateTaskRequest'] = _CREATETASKREQUEST
DESCRIPTOR.message_types_by_name['CreateTaskReply'] = _CREATETASKREPLY
DESCRIPTOR.message_types_by_name['NextSubtaskRequest'] = _NEXTSUBTASKREQUEST
DESCRIPTOR.message_types_by_name['NextSubtaskReply'] = _NEXTSUBTASKREPLY
DESCRIPTOR.message_types_by_name['ComputeRequest'] = _COMPUTEREQUEST
DESCRIPTOR.message_types_by_name['ComputeReply'] = _COMPUTEREPLY
DESCRIPTOR.message_types_by_name['VerifyRequest'] = _VERIFYREQUEST
DESCRIPTOR.message_types_by_name['VerifyReply'] = _VERIFYREPLY
DESCRIPTOR.message_types_by_name['RunBenchmarkRequest'] = _RUNBENCHMARKREQUEST
DESCRIPTOR.message_types_by_name['RunBenchmarkReply'] = _RUNBENCHMARKREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateTaskRequest = _reflection.GeneratedProtocolMessageType('CreateTaskRequest', (_message.Message,), dict(
  DESCRIPTOR = _CREATETASKREQUEST,
  __module__ = 'golem_task_api.proto.golem_task_api_pb2'
  # @@protoc_insertion_point(class_scope:golem_task_api.CreateTaskRequest)
  ))
_sym_db.RegisterMessage(CreateTaskRequest)

CreateTaskReply = _reflection.GeneratedProtocolMessageType('CreateTaskReply', (_message.Message,), dict(
  DESCRIPTOR = _CREATETASKREPLY,
  __module__ = 'golem_task_api.proto.golem_task_api_pb2'
  # @@protoc_insertion_point(class_scope:golem_task_api.CreateTaskReply)
  ))
_sym_db.RegisterMessage(CreateTaskReply)

NextSubtaskRequest = _reflection.GeneratedProtocolMessageType('NextSubtaskRequest', (_message.Message,), dict(
  DESCRIPTOR = _NEXTSUBTASKREQUEST,
  __module__ = 'golem_task_api.proto.golem_task_api_pb2'
  # @@protoc_insertion_point(class_scope:golem_task_api.NextSubtaskRequest)
  ))
_sym_db.RegisterMessage(NextSubtaskRequest)

NextSubtaskReply = _reflection.GeneratedProtocolMessageType('NextSubtaskReply', (_message.Message,), dict(
  DESCRIPTOR = _NEXTSUBTASKREPLY,
  __module__ = 'golem_task_api.proto.golem_task_api_pb2'
  # @@protoc_insertion_point(class_scope:golem_task_api.NextSubtaskReply)
  ))
_sym_db.RegisterMessage(NextSubtaskReply)

ComputeRequest = _reflection.GeneratedProtocolMessageType('ComputeRequest', (_message.Message,), dict(
  DESCRIPTOR = _COMPUTEREQUEST,
  __module__ = 'golem_task_api.proto.golem_task_api_pb2'
  # @@protoc_insertion_point(class_scope:golem_task_api.ComputeRequest)
  ))
_sym_db.RegisterMessage(ComputeRequest)

ComputeReply = _reflection.GeneratedProtocolMessageType('ComputeReply', (_message.Message,), dict(
  DESCRIPTOR = _COMPUTEREPLY,
  __module__ = 'golem_task_api.proto.golem_task_api_pb2'
  # @@protoc_insertion_point(class_scope:golem_task_api.ComputeReply)
  ))
_sym_db.RegisterMessage(ComputeReply)

VerifyRequest = _reflection.GeneratedProtocolMessageType('VerifyRequest', (_message.Message,), dict(
  DESCRIPTOR = _VERIFYREQUEST,
  __module__ = 'golem_task_api.proto.golem_task_api_pb2'
  # @@protoc_insertion_point(class_scope:golem_task_api.VerifyRequest)
  ))
_sym_db.RegisterMessage(VerifyRequest)

VerifyReply = _reflection.GeneratedProtocolMessageType('VerifyReply', (_message.Message,), dict(
  DESCRIPTOR = _VERIFYREPLY,
  __module__ = 'golem_task_api.proto.golem_task_api_pb2'
  # @@protoc_insertion_point(class_scope:golem_task_api.VerifyReply)
  ))
_sym_db.RegisterMessage(VerifyReply)

RunBenchmarkRequest = _reflection.GeneratedProtocolMessageType('RunBenchmarkRequest', (_message.Message,), dict(
  DESCRIPTOR = _RUNBENCHMARKREQUEST,
  __module__ = 'golem_task_api.proto.golem_task_api_pb2'
  # @@protoc_insertion_point(class_scope:golem_task_api.RunBenchmarkRequest)
  ))
_sym_db.RegisterMessage(RunBenchmarkRequest)

RunBenchmarkReply = _reflection.GeneratedProtocolMessageType('RunBenchmarkReply', (_message.Message,), dict(
  DESCRIPTOR = _RUNBENCHMARKREPLY,
  __module__ = 'golem_task_api.proto.golem_task_api_pb2'
  # @@protoc_insertion_point(class_scope:golem_task_api.RunBenchmarkReply)
  ))
_sym_db.RegisterMessage(RunBenchmarkReply)



_REQUESTORGOLEMAPP = _descriptor.ServiceDescriptor(
  name='RequestorGolemApp',
  full_name='golem_task_api.RequestorGolemApp',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=498,
  serialized_end=850,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateTask',
    full_name='golem_task_api.RequestorGolemApp.CreateTask',
    index=0,
    containing_service=None,
    input_type=_CREATETASKREQUEST,
    output_type=_CREATETASKREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='NextSubtask',
    full_name='golem_task_api.RequestorGolemApp.NextSubtask',
    index=1,
    containing_service=None,
    input_type=_NEXTSUBTASKREQUEST,
    output_type=_NEXTSUBTASKREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Verify',
    full_name='golem_task_api.RequestorGolemApp.Verify',
    index=2,
    containing_service=None,
    input_type=_VERIFYREQUEST,
    output_type=_VERIFYREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RunBenchmark',
    full_name='golem_task_api.RequestorGolemApp.RunBenchmark',
    index=3,
    containing_service=None,
    input_type=_RUNBENCHMARKREQUEST,
    output_type=_RUNBENCHMARKREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_REQUESTORGOLEMAPP)

DESCRIPTOR.services_by_name['RequestorGolemApp'] = _REQUESTORGOLEMAPP


_PROVIDERGOLEMAPP = _descriptor.ServiceDescriptor(
  name='ProviderGolemApp',
  full_name='golem_task_api.ProviderGolemApp',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=853,
  serialized_end=1036,
  methods=[
  _descriptor.MethodDescriptor(
    name='Compute',
    full_name='golem_task_api.ProviderGolemApp.Compute',
    index=0,
    containing_service=None,
    input_type=_COMPUTEREQUEST,
    output_type=_COMPUTEREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RunBenchmark',
    full_name='golem_task_api.ProviderGolemApp.RunBenchmark',
    index=1,
    containing_service=None,
    input_type=_RUNBENCHMARKREQUEST,
    output_type=_RUNBENCHMARKREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PROVIDERGOLEMAPP)

DESCRIPTOR.services_by_name['ProviderGolemApp'] = _PROVIDERGOLEMAPP

# @@protoc_insertion_point(module_scope)
