# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: golem_task_api/proto/golem_task_api.proto
# plugin: grpclib.plugin.main
import abc

import grpclib.const
import grpclib.client

import golem_task_api.proto.golem_task_api_pb2


class RequestorGolemAppBase(abc.ABC):

    @abc.abstractmethod
    async def CreateTask(self, stream):
        pass

    @abc.abstractmethod
    async def NextSubtask(self, stream):
        pass

    @abc.abstractmethod
    async def Verify(self, stream):
        pass

    @abc.abstractmethod
    async def RunBenchmark(self, stream):
        pass

    def __mapping__(self):
        return {
            '/golem_task_api.RequestorGolemApp/CreateTask': grpclib.const.Handler(
                self.CreateTask,
                grpclib.const.Cardinality.UNARY_UNARY,
                golem_task_api.proto.golem_task_api_pb2.CreateTaskRequest,
                golem_task_api.proto.golem_task_api_pb2.CreateTaskReply,
            ),
            '/golem_task_api.RequestorGolemApp/NextSubtask': grpclib.const.Handler(
                self.NextSubtask,
                grpclib.const.Cardinality.UNARY_UNARY,
                golem_task_api.proto.golem_task_api_pb2.NextSubtaskRequest,
                golem_task_api.proto.golem_task_api_pb2.NextSubtaskReply,
            ),
            '/golem_task_api.RequestorGolemApp/Verify': grpclib.const.Handler(
                self.Verify,
                grpclib.const.Cardinality.UNARY_UNARY,
                golem_task_api.proto.golem_task_api_pb2.VerifyRequest,
                golem_task_api.proto.golem_task_api_pb2.VerifyReply,
            ),
            '/golem_task_api.RequestorGolemApp/RunBenchmark': grpclib.const.Handler(
                self.RunBenchmark,
                grpclib.const.Cardinality.UNARY_UNARY,
                golem_task_api.proto.golem_task_api_pb2.RunBenchmarkRequest,
                golem_task_api.proto.golem_task_api_pb2.RunBenchmarkReply,
            ),
        }


class RequestorGolemAppStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.CreateTask = grpclib.client.UnaryUnaryMethod(
            channel,
            '/golem_task_api.RequestorGolemApp/CreateTask',
            golem_task_api.proto.golem_task_api_pb2.CreateTaskRequest,
            golem_task_api.proto.golem_task_api_pb2.CreateTaskReply,
        )
        self.NextSubtask = grpclib.client.UnaryUnaryMethod(
            channel,
            '/golem_task_api.RequestorGolemApp/NextSubtask',
            golem_task_api.proto.golem_task_api_pb2.NextSubtaskRequest,
            golem_task_api.proto.golem_task_api_pb2.NextSubtaskReply,
        )
        self.Verify = grpclib.client.UnaryUnaryMethod(
            channel,
            '/golem_task_api.RequestorGolemApp/Verify',
            golem_task_api.proto.golem_task_api_pb2.VerifyRequest,
            golem_task_api.proto.golem_task_api_pb2.VerifyReply,
        )
        self.RunBenchmark = grpclib.client.UnaryUnaryMethod(
            channel,
            '/golem_task_api.RequestorGolemApp/RunBenchmark',
            golem_task_api.proto.golem_task_api_pb2.RunBenchmarkRequest,
            golem_task_api.proto.golem_task_api_pb2.RunBenchmarkReply,
        )


class ProviderGolemAppBase(abc.ABC):

    @abc.abstractmethod
    async def Compute(self, stream):
        pass

    @abc.abstractmethod
    async def RunBenchmark(self, stream):
        pass

    def __mapping__(self):
        return {
            '/golem_task_api.ProviderGolemApp/Compute': grpclib.const.Handler(
                self.Compute,
                grpclib.const.Cardinality.UNARY_UNARY,
                golem_task_api.proto.golem_task_api_pb2.ComputeRequest,
                golem_task_api.proto.golem_task_api_pb2.ComputeReply,
            ),
            '/golem_task_api.ProviderGolemApp/RunBenchmark': grpclib.const.Handler(
                self.RunBenchmark,
                grpclib.const.Cardinality.UNARY_UNARY,
                golem_task_api.proto.golem_task_api_pb2.RunBenchmarkRequest,
                golem_task_api.proto.golem_task_api_pb2.RunBenchmarkReply,
            ),
        }


class ProviderGolemAppStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.Compute = grpclib.client.UnaryUnaryMethod(
            channel,
            '/golem_task_api.ProviderGolemApp/Compute',
            golem_task_api.proto.golem_task_api_pb2.ComputeRequest,
            golem_task_api.proto.golem_task_api_pb2.ComputeReply,
        )
        self.RunBenchmark = grpclib.client.UnaryUnaryMethod(
            channel,
            '/golem_task_api.ProviderGolemApp/RunBenchmark',
            golem_task_api.proto.golem_task_api_pb2.RunBenchmarkRequest,
            golem_task_api.proto.golem_task_api_pb2.RunBenchmarkReply,
        )
